@ECHO OFF
ECHO Copying DLL ...
xcopy /y "..\bin\debug\MyLocalBroadband.WebConfigManager.dll" .\GAC
ECHO Running WSPBuilder ...
.\WSPBuilder\wspbuilder -wspname MyLocalBroadband.WebConfigManager.wsp -BuildCas false -SolutionId c1eedb67-7dd0-4f3b-9a74-8c3586ff3c5c
ECHO Copying WSP to Setup ...
xcopy /y "..\WSP\MyLocalBroadband.WebConfigManager.wsp" ..\Setup