//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLocalBroadband.WSSSecurityManagement.Client.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/_vti_adm/HostingToolsSvc.asmx")]
        public string MyLocalBroadband_WSSSecurityManagement_Client_HostingTools_WS_HostingTools {
            get {
                return ((string)(this["MyLocalBroadband_WSSSecurityManagement_Client_HostingTools_WS_HostingTools"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/_vti_adm/HostingSharePointSvc.asmx")]
        public string MyLocalBroadband_WSSSecurityManagement_Client_HostingSharePoint_WS_SharePointService {
            get {
                return ((string)(this["MyLocalBroadband_WSSSecurityManagement_Client_HostingSharePoint_WS_SharePointServ" +
                    "ice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/_vti_adm/HostingSQLMembershipSvc.asmx")]
        public string MyLocalBroadband_WSSSecurityManagement_Client_HostingSQLMembership_WS_SQLMembershipService {
            get {
                return ((string)(this["MyLocalBroadband_WSSSecurityManagement_Client_HostingSQLMembership_WS_SQLMembersh" +
                    "ipService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/_vti_adm/HostingSQLRoleSvc.asmx")]
        public string MyLocalBroadband_WSSSecurityManagement_Client_HostingSQLRole_WS_SQLRoleService {
            get {
                return ((string)(this["MyLocalBroadband_WSSSecurityManagement_Client_HostingSQLRole_WS_SQLRoleService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080")]
        public string CentralAdminURL {
            get {
                return ((string)(this["CentralAdminURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dev.mylocalbroadband.com")]
        public string DNSURL {
            get {
                return ((string)(this["DNSURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string DNSIP {
            get {
                return ((string)(this["DNSIP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dev.mylocalbroadband.com")]
        public string NewSite_SiteURL {
            get {
                return ((string)(this["NewSite_SiteURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dev Site")]
        public string NewSite_SiteTitle {
            get {
                return ((string)(this["NewSite_SiteTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("My Local Broadband LLC Dev Site")]
        public string NewSite_SiteDescription {
            get {
                return ((string)(this["NewSite_SiteDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("STS#0")]
        public string NewSite_SiteTemplate {
            get {
                return ((string)(this["NewSite_SiteTemplate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1033")]
        public string NewSite_LCID {
            get {
                return ((string)(this["NewSite_LCID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dev.mylocalbroadband.com")]
        public string NewSite_WebApplicationName {
            get {
                return ((string)(this["NewSite_WebApplicationName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://MLBDevSearch")]
        public string NewSite_WebApplicationURL {
            get {
                return ((string)(this["NewSite_WebApplicationURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SecMembershipProvider")]
        public string NewSite_MembershipProviderName {
            get {
                return ((string)(this["NewSite_MembershipProviderName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rmiller@mylocalbroadband.com")]
        public string NewSite_OwnerLogin {
            get {
                return ((string)(this["NewSite_OwnerLogin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ryan")]
        public string NewSite_OwnerFirstName {
            get {
                return ((string)(this["NewSite_OwnerFirstName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Miller")]
        public string NewSite_OwnerLastName {
            get {
                return ((string)(this["NewSite_OwnerLastName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rmiller@mylocalbroadband.com")]
        public string NewSite_OwnerEmail {
            get {
                return ((string)(this["NewSite_OwnerEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("passw0rd#")]
        public string NewSite_OwnerPassword {
            get {
                return ((string)(this["NewSite_OwnerPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("q")]
        public string NewSite_PasswordQuestion {
            get {
                return ((string)(this["NewSite_PasswordQuestion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a")]
        public string NewSite_PasswordAnswer {
            get {
                return ((string)(this["NewSite_PasswordAnswer"]));
            }
        }
    }
}
