@ECHO OFF
ECHO Copying DLL ...
xcopy /y "..\bin\debug\MyLocalBroadband.WSSSecurityProvider.dll" .\GAC
ECHO Running WSPBuilder ...
.\WSPBuilder\wspbuilder -wspname MyLocalBroadband.WSSSecurityProvider.wsp -BuildCas false -SolutionId 93fe9d9e-b851-4ae3-9873-a6e0ff1b3b89
ECHO Copying WSP to Setup ...
xcopy /y "..\WSP\MyLocalBroadband.WSSSecurityProvider.wsp" ..\Setup